config/routes.rb
Rails.application.routes.draw do


  devise_for :users, skip: [:registrations]

  root 'static#homepage'

  resources :posts do
    member do
      patch :approve
    end
  end
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      patch :confirm
    end
  end
  
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end

end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <%= js add_gritter(flash[:notice], title: "Overtime Application Notification", sticky: false) %>
<% elsif flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Overtime Application Alert", sticky: false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Overtime Application Error", sticky: false) %>
<% end %>

app/views/shared/_header.html.erb
<div class="logo">
  <h1>Overtime Tracker</h1>
</div>

app/views/shared/_nav.html.erb
<% if current_user %>
	<ul class="custom-nav nav nav-tabs">
		<li class="<%= active?(root_url) %>">
	    <%= link_to "", root_url, class: "glyphicon glyphicon-home" %>
		</li>
		<% if current_user.employee? %>
			<li class="<%= active?(posts_path) %>">
	    	<%= link_to "Hours", posts_path %>
			</li>
			<li class="<%= active?(new_post_path) %>">
		    <%= link_to "Submit Hours", new_post_path, id: 'new_post_from_nav' %>
			</li>
		<% end %>
		<% if current_user.admin? %>
			<li class="<%= active?(audit_logs_path) %>">
		    <%= link_to "Audit Logs", audit_logs_path %>
			</li>
		<% end %>
		
		<li class="dropdown pull-right">
			 <a href="#" data-toggle="dropdown" class="dropdown-toggle">Options<strong class="caret"></strong></a>
			<ul class="dropdown-menu">
				<% if current_user.admin? %>
				<li><%= link_to "Admin Dashboard", admin_root_path %></li>
				<li class="divider"></li>
				<% end %>
				<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
			</ul>
		</li>
	</ul>
<% end %>