config/routes.rb
Rails.application.routes.draw do


  devise_for :users, skip: [:registrations]

  root 'static#homepage'

  resources :posts do
    member do
      patch :approve
    end
  end
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      patch :confirm
    end
  end
  
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end

end

app/models/post.rb
class Post < ApplicationRecord
  # Relationships
  belongs_to :user
  
  # Validations
  validates_presence_of :date, :daily_hours
  validates :daily_hours, numericality: { greater_than: 0 }
  
  # Enum
  enum status: { submitted: 0, approved: 1, rejected: 2 }
  
  # Scope
  scope :posts_by, ->(user) { where(user_id: user.id) }

  # Filter
  after_save :confirm_audit_log, if: :submitted?
  after_save :reset_audit_log, if: :rejected? 
  
  private
    
    def confirm_audit_log
      audit_log = AuditLog.where(user_id: self.user_id, 
                                 start_date: (self.date - 7.days..self.date)).last
      audit_log.confirmed! if audit_log
    end
    
    def reset_audit_log
      audit_log = AuditLog.where(user_id: self.user_id, 
                                 start_date: (self.date - 7.days..self.date)).last
      audit_log.pending! if audit_log
    end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :approve, :destroy]
  
  def index
    @posts = Post.posts_by(current_user).order(:id).page(params[:page]).per(10)
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    
    if @post.save
      redirect_to @post, notice: "Your post was created successfully."
    else
      render :new
    end
  end
  
  def edit
    authorize @post
  end
  
  def update
    authorize @post
    
    if @post.update(post_params)
      redirect_to @post, notice: "Your post was updated successfully."
    else
      render :edit
    end
  end
  
  def approve
    authorize @post
    
    @post.approved!
    redirect_to root_path, notice: "Overtime request is approved!"
  end
  
  def show
  end
  
  def destroy
    if @post.delete
      redirect_to posts_path, notice: "Your post was deleted."
    end
  end
  
  private
  
    def set_post
      @post = Post.find(params[:id])
    end
    
    def post_params
      params.require(:post).permit(:date, :work_performed, :status, :daily_hours)
    end
  

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, class: "form-horizontal" do |f| %>
  
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, title: "Invalid Post", sticky: false) %>
    <% end %>
  <% end %>
  
  <div class="form-group">
    <%= f.label :date, class: "col-sm-2 control-label" %>
    <%= f.date_field :date, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :daily_hours, class: "col-sm-2 control-label" %>
    <%= f.number_field :daily_hours, step: 0.1, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :work_performed, "Work Performed", class: "col-sm-2 control-label" %>
    <%= f.text_area :work_performed, class: "form-control" %>
  </div>
  
  
  <%= render partial: 'status', locals: { f: f } if current_user.admin? %>
  
  <%= f.submit 'Save', class: "btn btn-primary btn-block" %>

<% end %>

app/views/posts/_post.html.erb
<tr>
  <td><%= post.date %></td>
  <td><%= post.daily_hours %></td>
  <td class="hidden-xs"><%= link_to truncate(post.work_performed), post %></td>
  <td><%= status_label(post.status) %></td>
  <td>
    <%= link_to '', edit_post_path(post), id: "edit_#{post.id}",
                    class: "glyphicon glyphicon-edit index-icon" if policy(post).update? %>
  </td>
  <td>
    <%= link_to '', post_path(post), method: :delete, 
                    class: "glyphicon glyphicon-remove index-icon",
                    id: "delete_post_#{post.id}_from_index", 
                    data: { confirm: "Please Confirm Entry Removal."} %>
  </td>
</tr>

app/views/posts/_status.html.erb
<div class="form-group">
  <%= f.radio_button :status, 'submitted' %>
  <%= f.label :status, 'Submitted' %>

  <%= f.radio_button :status, 'approved' %>
  <%= f.label :status, 'Approved' %>
  
  <%= f.radio_button :status, 'rejected' %>    
  <%= f.label :status, 'Rejected' %>
</div>

app/views/posts/edit.html.erb
<h3>Edit Entry</h3>

<%= render 'form' %>

app/views/posts/index.html.erb
<h3>My Entries</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Hours Requested</th>
      <th class="hidden-xs">Work Performed</th>
      <th>Status</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody id="posts">
    <%= render @posts %>
  </tbody>
</table>

<div id="paginator">
  <%= paginate @posts, remote: true %>
</div>

app/views/posts/index.js.erb
$('#posts').html('<%= escape_javascript render(@posts) %>');
$('#paginator').html('<%= escape_javascript(paginate(@posts, remote: true).to_s) %>');

app/views/posts/new.html.erb
<h3>New Overtime Request</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="">
  <h2><%= @post.date %></h2>
</div>

<div class="well">
  <div>
    <h3><span>Hours Requested:</span> <%= @post.daily_hours %></h3>
  </div>
  
  <div>
    <h3><span>Work Performed:</span> <%= @post.work_performed %></h3>
  </div>
  
  <div>
    <h3><span>Employee:</span> <%= @post.user.full_name %></h3>
  </div>
  
  <div>
    <h3><span>Current Stage of Approval: </span> <%= @post.status.titleize %></h3>
  </div>
</div>

<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-info" if policy(@post).update? %>